# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    bundles:
        - CampaignChainOperationTwitterBundle
    assets:
        campaignchain_operation_twitter_css:
            inputs:
                - '@CampaignChainOperationTwitterBundle/Resources/public/css/base.css'
twig:
    form:
        resources:
            - 'CampaignChainOperationTwitterBundle:Form:fields.html.twig'