# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_operation_twitter_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CampaignChainOperationTwitterBundle:Default:index }
