# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.operation.twitter.update_status:
        bundle_name: "campaignchain/operation-twitter"
        module_identifier: "campaignchain-twitter-update-status"
        form_type: "CampaignChain\\Operation\\TwitterBundle\\Form\\Type\\UpdateStatusOperationType"

services:
    campaignchain.job.operation.twitter.update_status:
        class: CampaignChain\Operation\TwitterBundle\Job\UpdateStatus
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.twitter.update_status:
        class: CampaignChain\Operation\TwitterBundle\Job\ReportUpdateStatus
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.twitter.status:
            class: CampaignChain\Operation\TwitterBundle\EntityService\Status
            arguments: [ @doctrine.orm.entity_manager ]